# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/List_Selector/list_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bg_widget = QtWidgets.QWidget(Dialog)
        self.bg_widget.setStyleSheet("QWidget#bg_widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.verticalWidget_2 = QtWidgets.QWidget(self.bg_widget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(625, 200, 350, 100))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_4.setStyleSheet("font: 75 25pt \"Ubuntu\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.public_list_button = QtWidgets.QPushButton(self.bg_widget)
        self.public_list_button.setGeometry(QtCore.QRect(650, 380, 300, 50))
        self.public_list_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.public_list_button.setObjectName("public_list_button")
        self.private_list_button = QtWidgets.QPushButton(self.bg_widget)
        self.private_list_button.setGeometry(QtCore.QRect(650, 480, 300, 50))
        self.private_list_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.private_list_button.setObjectName("private_list_button")
        self.back = QtWidgets.QPushButton(self.bg_widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 60, 40))
        self.back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 28px;")
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.bg_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">Select your option</span></p></body></html>"))
        self.public_list_button.setText(_translate("Dialog", "Public List"))
        self.private_list_button.setText(_translate("Dialog", "Private List"))
        self.back.setText(_translate("Dialog", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
