# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/public_list/public_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bg_widget = QtWidgets.QWidget(Dialog)
        self.bg_widget.setStyleSheet("QWidget#bg_widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.public_list_view = QtWidgets.QListWidget(self.bg_widget)
        self.public_list_view.setGeometry(QtCore.QRect(20, 50, 800, 751))
        self.public_list_view.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.public_list_view.setStyleSheet("QListView {\n"
"    border: none;\n"
"    outline: none;\n"
"    border-radius: 10px;\n"
"       background-color: white;\n"
"       padding: 10px;\n"
"}\n"
"QListView::item {\n"
"       border: none;\n"
"    border-radius: 10px;\n"
"       padding: 10px;\n"
"}\n"
"QListView::item:selected {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"    /*background-color: #f0f0f0;*/\n"
"}\n"
"QListView::item:hover {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.public_list_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.public_list_view.setLineWidth(1)
        self.public_list_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.public_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.public_list_view.setSelectionRectVisible(False)
        self.public_list_view.setObjectName("private_list_view")
        self.back = QtWidgets.QPushButton(self.bg_widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 60, 40))
        self.back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 28px;")
        self.back.setObjectName("back")
        self.show_image = QtWidgets.QLabel(self.bg_widget)
        self.show_image.setGeometry(QtCore.QRect(880, 210, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_image.sizePolicy().hasHeightForWidth())
        self.show_image.setSizePolicy(sizePolicy)
        self.show_image.setText("")
        self.show_image.setAlignment(QtCore.Qt.AlignCenter)
        self.show_image.setOpenExternalLinks(True)
        self.show_image.setObjectName("show_image")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bg_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 810, 801, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_button.sizePolicy().hasHeightForWidth())
        self.delete_button.setSizePolicy(sizePolicy)
        self.delete_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.horizontalLayout.addWidget(self.bg_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.back.setText(_translate("Dialog", "<"))
        self.add_button.setText(_translate("Dialog", "Add to Private List"))
        self.delete_button.setText(_translate("Dialog", "Delete Destination"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
