# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/private_list/private_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bg_widget = QtWidgets.QWidget(Dialog)
        self.bg_widget.setStyleSheet("QWidget#bg_widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.private_list_view = QtWidgets.QListWidget(self.bg_widget)
        self.private_list_view.setGeometry(QtCore.QRect(20, 50, 800, 751))
        self.private_list_view.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.private_list_view.setStyleSheet("QListView {\n"
"    border: none;\n"
"    outline: none;\n"
"    border-radius: 10px;\n"
"       background-color: white;\n"
"       padding: 10px;\n"
"}\n"
"QListView::item {\n"
"       border: none;\n"
"    border-radius: 10px;\n"
"       padding: 10px;\n"
"}\n"
"QListView::item:selected {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"    /*background-color: #f0f0f0;*/\n"
"}\n"
"QListView::item:hover {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.private_list_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.private_list_view.setLineWidth(1)
        self.private_list_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.private_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.private_list_view.setSelectionRectVisible(False)
        self.private_list_view.setObjectName("private_list_view")
        self.start_date_picker = QtWidgets.QDateEdit(self.bg_widget)
        self.start_date_picker.setGeometry(QtCore.QRect(880, 300, 141, 26))
        self.start_date_picker.setStyleSheet("QDateEdit{\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 13px;\n"
"    font-size: 20px;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}\n"
"QDateEdit::drop-down {\n"
"    image: url(:/drop_down_icon/drop_down.png);\n"
"    width: 26px;\n"
"    height: 26px;\n"
"}")
        self.start_date_picker.setCalendarPopup(True)
        self.start_date_picker.setObjectName("start_date_picker")
        self.geolocation_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.geolocation_line_edit.setGeometry(QtCore.QRect(880, 60, 300, 30))
        self.geolocation_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.geolocation_line_edit.setObjectName("geolocation_line_edit")
        self.label = QtWidgets.QLabel(self.bg_widget)
        self.label.setGeometry(QtCore.QRect(890, 40, 101, 20))
        self.label.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bg_widget)
        self.label_2.setGeometry(QtCore.QRect(890, 100, 41, 20))
        self.label_2.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.title_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.title_line_edit.setGeometry(QtCore.QRect(880, 120, 300, 30))
        self.title_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.title_line_edit.setObjectName("title_line_edit")
        self.image_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.image_line_edit.setGeometry(QtCore.QRect(880, 180, 300, 30))
        self.image_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.image_line_edit.setObjectName("image_line_edit")
        self.description_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.description_line_edit.setGeometry(QtCore.QRect(880, 240, 300, 30))
        self.description_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.description_line_edit.setObjectName("description_line_edit")
        self.label_3 = QtWidgets.QLabel(self.bg_widget)
        self.label_3.setGeometry(QtCore.QRect(890, 160, 51, 20))
        self.label_3.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bg_widget)
        self.label_4.setGeometry(QtCore.QRect(890, 220, 91, 20))
        self.label_4.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bg_widget)
        self.label_5.setGeometry(QtCore.QRect(890, 280, 111, 20))
        self.label_5.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_5.setObjectName("label_5")
        self.end_date_picker = QtWidgets.QDateEdit(self.bg_widget)
        self.end_date_picker.setGeometry(QtCore.QRect(1040, 300, 141, 26))
        self.end_date_picker.setStyleSheet("QDateEdit{\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 13px;\n"
"    font-size: 20px;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}\n"
"QDateEdit::drop-down {\n"
"    image: url(:/drop_down_icon/drop_down.png);\n"
"    width: 26px;\n"
"    height: 26px;\n"
"}")
        self.end_date_picker.setCalendarPopup(True)
        self.end_date_picker.setObjectName("end_date_picker")
        self.label_6 = QtWidgets.QLabel(self.bg_widget)
        self.label_6.setGeometry(QtCore.QRect(1050, 280, 101, 20))
        self.label_6.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_6.setObjectName("label_6")
        self.back = QtWidgets.QPushButton(self.bg_widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 60, 40))
        self.back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 28px;")
        self.back.setObjectName("back")
        self.show_image = QtWidgets.QLabel(self.bg_widget)
        self.show_image.setGeometry(QtCore.QRect(880, 360, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_image.sizePolicy().hasHeightForWidth())
        self.show_image.setSizePolicy(sizePolicy)
        self.show_image.setText("")
        self.show_image.setAlignment(QtCore.Qt.AlignCenter)
        self.show_image.setOpenExternalLinks(True)
        self.show_image.setObjectName("show_image")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bg_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 810, 801, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.make_favourite_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.make_favourite_button.sizePolicy().hasHeightForWidth())
        self.make_favourite_button.setSizePolicy(sizePolicy)
        self.make_favourite_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.make_favourite_button.setObjectName("make_favourite_button")
        self.horizontalLayout_2.addWidget(self.make_favourite_button)
        self.clear_selection_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_selection_button.sizePolicy().hasHeightForWidth())
        self.clear_selection_button.setSizePolicy(sizePolicy)
        self.clear_selection_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.clear_selection_button.setObjectName("clear_selection_button")
        self.horizontalLayout_2.addWidget(self.clear_selection_button)
        self.delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_button.sizePolicy().hasHeightForWidth())
        self.delete_button.setSizePolicy(sizePolicy)
        self.delete_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.bg_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1280, 70, 221, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_button.sizePolicy().hasHeightForWidth())
        self.update_button.setSizePolicy(sizePolicy)
        self.update_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.update_button.setObjectName("update_button")
        self.verticalLayout.addWidget(self.update_button)
        self.clear_fields_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_fields_button.sizePolicy().hasHeightForWidth())
        self.clear_fields_button.setSizePolicy(sizePolicy)
        self.clear_fields_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.clear_fields_button.setObjectName("clear_fields_button")
        self.verticalLayout.addWidget(self.clear_fields_button)
        self.horizontalLayout.addWidget(self.bg_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.geolocation_line_edit, self.title_line_edit)
        Dialog.setTabOrder(self.title_line_edit, self.image_line_edit)
        Dialog.setTabOrder(self.image_line_edit, self.description_line_edit)
        Dialog.setTabOrder(self.description_line_edit, self.start_date_picker)
        Dialog.setTabOrder(self.start_date_picker, self.end_date_picker)
        Dialog.setTabOrder(self.end_date_picker, self.add_button)
        Dialog.setTabOrder(self.add_button, self.update_button)
        Dialog.setTabOrder(self.update_button, self.private_list_view)
        Dialog.setTabOrder(self.private_list_view, self.back)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_date_picker.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Geolocation:</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Title:</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Image:</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Description:</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Start vacation:</p></body></html>"))
        self.end_date_picker.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>End vacation:</p></body></html>"))
        self.back.setText(_translate("Dialog", "<"))
        self.make_favourite_button.setText(_translate("Dialog", "Make Favourite"))
        self.clear_selection_button.setText(_translate("Dialog", "Clear Selection"))
        self.delete_button.setText(_translate("Dialog", "Delete Destination"))
        self.add_button.setText(_translate("Dialog", "Add Destination"))
        self.update_button.setText(_translate("Dialog", "Update Destination"))
        self.clear_fields_button.setText(_translate("Dialog", "Clear Fields"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
