# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Login/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bg_widget = QtWidgets.QWidget(Dialog)
        self.bg_widget.setStyleSheet("QWidget#bg_widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 193, 234, 255), stop:1 rgba(255, 193, 234, 255));\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.verticalWidget = QtWidgets.QWidget(self.bg_widget)
        self.verticalWidget.setGeometry(QtCore.QRect(625, 150, 350, 100))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setStyleSheet("font: 75 25pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.login_button = QtWidgets.QPushButton(self.bg_widget)
        self.login_button.setGeometry(QtCore.QRect(650, 470, 300, 50))
        self.login_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.login_button.setObjectName("login_button")
        self.username_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.username_line_edit.setGeometry(QtCore.QRect(650, 320, 300, 30))
        self.username_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.username_line_edit.setObjectName("username_line_edit")
        self.password_line_edit = QtWidgets.QLineEdit(self.bg_widget)
        self.password_line_edit.setGeometry(QtCore.QRect(650, 400, 300, 30))
        self.password_line_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"padding-left: 10px;")
        self.password_line_edit.setObjectName("password_line_edit")
        self.label_2 = QtWidgets.QLabel(self.bg_widget)
        self.label_2.setGeometry(QtCore.QRect(660, 300, 80, 20))
        self.label_2.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.bg_widget)
        self.label_3.setGeometry(QtCore.QRect(660, 380, 80, 20))
        self.label_3.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.warning_label = QtWidgets.QLabel(self.bg_widget)
        self.warning_label.setGeometry(QtCore.QRect(656, 440, 291, 20))
        self.warning_label.setStyleSheet("color: red;\n"
"font: 25 12pt \"Umpush\";")
        self.warning_label.setObjectName("warning_label")
        self.back = QtWidgets.QPushButton(self.bg_widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 60, 40))
        self.back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 28px;")
        self.back.setObjectName("back")
        self.verticalLayout_2.addWidget(self.bg_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_line_edit, self.password_line_edit)
        Dialog.setTabOrder(self.password_line_edit, self.login_button)
        Dialog.setTabOrder(self.login_button, self.back)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;color: white\">Log In</span></p></body></html>"))
        self.login_button.setText(_translate("Dialog", "Log In"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span>Username:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.warning_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.back.setText(_translate("Dialog", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
